In [11]:
import numpy as np
from numpy import linalg as LA
np.set_printoptions(precision=3, suppress=True)

In [12]:
ket0=np.array([[1],[0]]) # |0>
ket1=np.array([[0],[1]]) # |1>


In [13]:
print("Ket |0>:\n", ket0)
print("\nKet |1>:\n", ket1)


Ket |0>:
 [[1]
 [0]]

Ket |1>:
 [[0]
 [1]]


In Dirac notation (bra-ket), a ket |ψ⟩ is a column vector in a Hilbert space. The two basis states of a qubit are:

|0⟩ = [1] |1⟩ = [0] [0] [1]

These are orthonormal: ⟨0|0⟩ = 1, ⟨1|1⟩ = 1, and ⟨0|1⟩ = 0. Any qubit state lives in ℂ², spanned by these two vectors. Shape here is (2,1) — a proper column vector, not a 1D array, which matters for matrix multiplication.

In [14]:
# bra vectors  (conjugate transpose)
bra0=ket0.conj().T
bra1=ket1.conj().T


In [15]:
print("\nBra <0|:\n", bra0)
print("\nBra <1|:\n", bra1)


Bra <0|:
 [[1 0]]

Bra <1|:
 [[0 1]]


A bra ⟨ψ| is the conjugate transpose (Hermitian adjoint) of the ket:

⟨ψ| = (|ψ⟩)† = (|ψ⟩*)ᵀ


For real vectors (no imaginary parts), this is just a transpose. So:

⟨0| = [1, 0] ⟨1| = [0, 1]

.conj() takes complex conjugate; .T transposes. Together they form the dagger operation (†).





In [16]:
# inner product
inner = bra1 @ ket1
print("⟨1|1⟩ =", inner)

⟨1|1⟩ = [[1]]


In [17]:
# Superposition State [∣ψ⟩=1/sqrt(2) (​∣0⟩+∣1⟩​)]
psi=(ket0+ket1)/np.sqrt(2)
print("State |psi>:\n", psi)

norm=psi.conj().T@psi
print("Normalization check:", norm)

State |psi>:
 [[0.707]
 [0.707]]
Normalization check: [[1.]]


A qubit can exist in a superposition - a linear combination of basis states:

|ψ⟩ = α|0⟩ + β|1⟩ where |α|² + |β|² = 1

Here α = β = 1/√2, giving the equal superposition (the |+⟩ state):

|ψ⟩ = (1/√2)(|0⟩ + |1⟩) = [1/√2] [1/√2]

The normalization check computes ⟨ψ|ψ⟩:

⟨ψ|ψ⟩ = (1/√2)² + (1/√2)² = 1/2 + 1/2 = 1 

Physical meaning: measuring this state gives |0⟩ with probability |α|² = 0.5, and |1⟩ with probability |β|² = 0.5.

In [18]:
# Operators (Pauli Matrices)

sigma_x=np.array([[0,1],[1,0]])
sigma_y=np.array([[0,-1j],[1j,0]])
sigma_z=np.array([[1,0],[0,-1]])
I2=np.identity(2) #Identity Matrix 
print("Identity Matrix (2x2):\n", I2, "\n")

print("Pauli X:\n", sigma_x, "\n")
print("Pauli Y:\n", sigma_y, "\n")
print("Pauli Z:\n", sigma_z, "\n")

Identity Matrix (2x2):
 [[1. 0.]
 [0. 1.]] 

Pauli X:
 [[0 1]
 [1 0]] 

Pauli Y:
 [[ 0.+0.j -0.-1.j]
 [ 0.+1.j  0.+0.j]] 

Pauli Z:
 [[ 1  0]
 [ 0 -1]] 



Pauli matrices are 2×2 Hermitian unitary matrices representing spin-½ observables. They are:

σₓ = [0 1] σ_y = [0 -i] σ_z = [1 0] [1 0] [i 0] [0 -1]

Key properties of all Pauli matrices:

- Hermitian: σ† = σ (observables in QM must be Hermitian)

- Unitary: σσ† = I (norm-preserving)

- Eigenvalues: always ±1 (only possible measurement outcomes

- Squaring: σₓ² = σ_y² = σ_z² = I

- Commutation: [σₓ, σ_y] = 2i σ_z (cyclic)

1j in Python is the imaginary unit i. σ_y contains purely imaginary entries; it will give complex intermediate results.



In [19]:
# Expectation Value (⟨A⟩=⟨ψ∣A∣ψ⟩)

exp_x=psi.conj().T@sigma_x@psi
# exp_y = psi.conj().T @ sigma_y @ psi
# exp_z = ket0.conj().T @ sigma_z @ ket0

print("<sigma_x> =", exp_x)

<sigma_x> = [[1.]]


The expectation value of observable A in state |ψ⟩ is the quantum analog of a statistical average:

⟨A⟩ = ⟨ψ|A|ψ⟩ (sandwich product: bra · operator · ket)

For |ψ⟩ = (1/√2)[1,1]ᵀ and σₓ = [[0,1],[1,0]]:

σₓ|ψ⟩ = [0 1][1/√2] = [1/√2] [1 0][1/√2] [1/√2] 
⟨σₓ⟩ = ⟨ψ|σₓ|ψ⟩ = [1/√2, 1/√2]·[1/√2] = 1/2 + 1/2 = 1 [1/√2]

Result ⟨σₓ⟩ = 1 means the |+⟩ state is an eigenstate of σₓ with eigenvalue +1. Average measurement of σₓ is always +1.

In [20]:
# Density Matrix - Pure State {ρ=∣ψ⟩⟨ψ∣}

rho_pure=psi@psi.conj().T
print("Density Matrix (Pure State):\n", rho_pure)

print("Trace:", np.trace(rho_pure))
purity=np.trace(rho_pure @ rho_pure)
print("Purity Tr(rho^2) =", purity)

Density Matrix (Pure State):
 [[0.5 0.5]
 [0.5 0.5]]
Trace: 0.9999999999999998
Purity Tr(rho^2) = 0.9999999999999996


The density matrix ρ generalizes the state vector. For a pure state:

ρ = |ψ⟩⟨ψ| (outer product: column × row)
ρ = [1/√2] · [1/√2, 1/√2] = [1/2 1/2] [1/√2] [1/2 1/2]
Key identities that are verified in the code:

Tr(ρ) = 1 (normalization — always) Tr(ρ²) = 1 (purity = 1 for pure states) ρ² = ρ (idempotent for pure states) ρ† = ρ (Hermitian)
The outer product psi @ psi.conj().T has shape (2,1)@(1,2) = (2,2). This is why ket must be (2,1) not (2,) — 1D arrays would give a scalar.



In [25]:
# Mixed State [Suppose: |0⟩ with probability 0.5 and |1⟩ with probability 0.5]

rho_mixed=0.5*(ket0 @ ket0.conj().T)+ 0.5*(ket1 @ ket1.conj().T)
print("Mixed state density matrix:\n", rho_mixed)
print("Purity:", np.trace(rho_mixed @ rho_mixed))

Mixed state density matrix:
 [[0.5 0. ]
 [0.  0.5]]
Purity: 0.5


A mixed state represents classical uncertainty — we know the system is in |0⟩ or |1⟩ but not which. It is a classical probability mixture:

ρ_mixed = Σᵢ pᵢ |ψᵢ⟩⟨ψᵢ| where Σpᵢ = 1, pᵢ ≥ 0
ρ_mixed = 0.5|0⟩⟨0| + 0.5|1⟩⟨1| = 0.5[1 0] + 0.5[0 0] = [0.5 0 ] [0 0] [0 1] [0 0.5] = (1/2)I₂
Tr(ρ_mixed²) = Tr[(1/4)I] = 1/4 + 1/4 = 0.5 < 1 ← mixed!

Purity is between 1/d (maximally mixed, d = dimension) and 1 (pure). Here 1/2 ≤ purity ≤ 1 for a qubit, and 0.5 is the maximally mixed state.

In [26]:
# expectation value (using Trace formula: <A>=Tr(ρA))
exp_trace=np.trace(rho_pure @ sigma_z)
print("Expectation via trace:", exp_trace)

Expectation via trace: 0.0


exp_trace = np.trace(rho_pure @ sigma_z)
For density matrices, the expectation value uses the trace formula:

⟨A⟩ = Tr(ρA)
This is equivalent to ⟨ψ|A|ψ⟩ for pure states. Here:

ρ σ_z = [1/2 1/2][1 0] = [1/2 -1/2] [1/2 1/2][0 -1] [1/2 -1/2] Tr(ρ σ_z) = 1/2 + (-1/2) = 0

⟨σ_z⟩ = 0 for the |+⟩ state, meaning measuring spin-z gives +1 or −1 with equal probability. Makes physical sense — |+⟩ is an equal superposition along 

In [27]:
# Unitary Evolution {ρ → UρU†}
H=(1/np.sqrt(2))*np.array([[1,1],[1,-1]])
rho_evolved=H @ rho_pure @ H.conj().T
print("Evolved density matrix:\n", rho_evolved)

Evolved density matrix:
 [[1. 0.]
 [0. 0.]]


The Hadamard gate H is a unitary operator. Time evolution (or gate action) transforms density matrices as:

ρ' = U ρ U† (unitary conjugation)
H = (1/√2)[1 1] H† = H (H is its own inverse: H² = I) [1 -1]
Applying H to the pure state |+⟩ = (1/√2)(|0⟩+|1⟩):

H|+⟩ = |0⟩ → ρ' = |0⟩⟨0| = [1 0] [0 0]

The evolved density matrix is now the pure state |0⟩. The Hadamard maps the X-basis back to the Z-basis.

In [30]:
# Tensor product utility
def tensor(a, b):
    return np.kron(a, b)

bell=(tensor(ket0, ket0)+ tensor(ket1, ket1))/np.sqrt(2) #create bell state



For a composite system of two qubits, states live in ℂ² ⊗ ℂ² = ℂ⁴. The tensor product of states is:

|ψ₁⟩ ⊗ |ψ₂⟩ ←→ np.kron(ket1, ket2)
|Φ⁺⟩ = (1/√2)(|00⟩ + |11⟩) = (1/√2)[1, 0, 0, 1]ᵀ

This is a Bell state — maximally entangled. Measuring either qubit instantly determines the other, regardless of distance.



In [31]:
rho_bell= bell @ bell.conj().T

#partial trace over second qubit
rho_A=np.zeros((2,2), dtype=complex)

for i in range(2):
    rho_A+=rho_bell[i::2,i::2]

print("Reduced density matrix of subsystem A:\n", rho_A)
print("Purity of subsystem:", np.trace(rho_A @ rho_A))

Reduced density matrix of subsystem A:
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
Purity of subsystem: (0.4999999999999998+0j)


The partial trace over subsystem B gives the reduced density matrix of A alone:

ρ_A = Tr_B(ρ_AB) = Σⱼ (I_A ⊗ ⟨j|_B) ρ_AB (I_A ⊗ |j⟩_B)
The slicing trick rho_bell[i::2, i::2] selects the (i,i)-th 2×2 block of the 4×4 matrix, which corresponds to fixing the second qubit basis state. Summing over i=0,1 performs the trace over B.

ρ_A = (1/2)[1 0] = (1/2)I₂ [0 1]
Tr(ρ_A²) = Tr[(1/4)I] = 0.5 ← maximally mixed!